services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/python/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - PYTHONPATH=/app
    ports:
      - "8080:8080"
    command: python telegram/telegram_bot.py
    stdin_open: true
    tty: true
  
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/vue/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
